name = "yangbowen-blog"
main = "./src/index.js"
compatibility_date = "2023-12-01"

# 环境变量（生产环境建议在Dashboard中设置）
[env.production.vars]
AMAP_API_KEY = "31280bbb46f491bd85df213f90d01f31"
MINIMAX_TOKEN = "eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJHcm91cE5hbWUiOiLmnajljZrmlociLCJVc2VyTmFtZSI6IuadqOWNmuaWhyIsIkFjY291bnQiOiIiLCJTdWJqZWN0SUQiOiIxOTIyMjE4MTk5MjY5NTExNjM0IiwiUGhvbmUiOiIxOTIzMzgxNzg1NCIsIkdyb3VwSUQiOiIxOTIyMjE4MTk5MjY1MzE3MzMwIiwiUGFnZU5hbWUiOiIiLCJNYWlsIjoiIiwiQ3JlYXRlVGltZSI6IjIwMjUtMDYtMDkgMTE6MjY6MzciLCJUb2tlblR5cGUiOjEsImlzcyI6Im1pbmltYXgifQ.LgLhhOff8zk8NqpwglUQuxI7XmhqKUMEqt83lS8snE17WUMi68_JARBhMRAJ3Uhi0Brp2_d6UC3_e8O2t5rMG6KR7pZh0oYcPDAQpfcH4c0W3BeibSDM8YKSBi7y_i4V5oNAnyZ4kTwgQXEm-Ojzco5UBAHSiPQcozifnM_G45ODAqf2H8QCMMeEqeJkecEvjA2Q9KxORgCHQNgV4_kqLUaR8CPrgyrckv4K2rY5PmnUZTtHNdmXxQ2WkKDvq4DjNEyvLqDDaQEE_6QKu75C6tlWbyqzJ-Pr7ucbaawFu5UN9bUUCBSfX1osKxEymqTHOwbdnO-jeOOSv5nsHHjq8g"

# 资源限制
[limits]
cpu_ms = 50
memory_mb = 128

# 自定义域名（可选）
# [[env.production.routes]]
# pattern = "blog.yangbowen.com/*"
# zone_name = "yangbowen.com"

# KV存储（用于文章缓存，可选）
# [[kv_namespaces]]
# binding = "POSTS_CACHE"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"